[package]
name = "lsp"
version = "0.1.0"
edition = "2024"

[dependencies]
tokio = { version = "1", features = ["rt-multi-thread", "macros", "io-std"] }
tower-lsp = "0.20"
gluegen = { path = "../gluegen" }
log = "0.4.28"
